import { createContext, useContext, useState, ReactNode } from "react";

export type Lang = "ar" | "en";

const translations = {
  en: {
    dashboard: "Dashboard",
    spaces: "Spaces",
    timeline: "Timeline",
    history: "History",
    members: "Members",
    senders: "Senders",
    settings: "Settings",
    menu: "Menu",
    workspace: "Workspace",
    lightMode: "Light mode",
    darkMode: "Dark mode",
    mySpaces: "My Spaces",
    welcomeBack: "Welcome back",
    signInSubtitle: "Sign in to your workspace account",
    email: "Email",
    password: "Password",
    signIn: "Sign in",
    signingIn: "Signing in...",
    noAccount: "Don't have an account?",
    signUp: "Sign up",
    createAccount: "Create Account",
    alreadyHaveAccount: "Already have an account?",
    fullName: "Full Name",
    yourFullName: "Your full name",
    confirmPassword: "Confirm Password",
    minChars: "Min. 6 characters",
    signingUp: "Creating account...",
    joinWorkspace: "Sign up to join your team workspace",
    newSpace: "New Space",
    searchSpaces: "Search spaces...",
    createSpace: "Create Space",
    spaceName: "Name",
    spaceDesc: "Description",
    spaceColor: "Color",
    noSpacesFound: "No spaces found",
    createFirstSpace: "Create your first space to start organizing tasks.",
    notInAnySpace: "You haven't been added to any spaces yet.",
    tasks: "tasks",
    membersLabel: "members",
    creating: "Creating...",
    cancel: "Cancel",
    overview: "Overview",
    tasksTab: "Tasks",
    timelineTab: "Timeline",
    membersTab: "Members",
    data: "Data",
    filesLinks: "Files & Links",
    newFolder: "New Folder",
    addLink: "Add Link",
    createFolder: "Create Folder",
    emptyFolder: "Empty folder",
    noFilesYet: "No files or links yet",
    noFilesDesc: "Create folders and add links to organize your space resources.",
    noFilesAdded: "No files or links have been added yet.",
    newTask: "New Task",
    createTask: "Create Task",
    taskTitle: "Task title...",
    description: "Description (optional)",
    status: "Status",
    priority: "Priority",
    deadline: "Deadline",
    estimatedHours: "Est. Hours",
    estimatedHoursLabel: "Estimated Hours",
    assignMembers: "Assign Members",
    assignees: "Assignees",
    sender: "Sender",
    senderFrom: "Sender (from manager)",
    noTasksYet: "No tasks yet",
    noTaskFound: "Task not found",
    progress: "Progress",
    activity: "Activity",
    writeComment: "Write a comment...",
    sendReminder: "Send Reminder",
    backToSpace: "Back to space",
    deleteTask: "Delete Task",
    deleteSpace: "Delete Space",
    profileSettings: "Profile Settings",
    webhookSettings: "Webhook Settings",
    saveChanges: "Save Changes",
    saving: "Saving...",
    loading: "Loading...",
    delete: "Delete",
    edit: "Edit",
    add: "Add",
    save: "Save",
    search: "Search...",
    noResults: "No results",
    overdue: "Overdue",
    dueSoon: "Due Soon",
    inProgress: "In Progress",
    done: "Done",
    blocked: "Blocked",
    todo: "To Do",
    review: "Review",
    today: "Today",
    tomorrow: "Tomorrow",
    dueToday: "Due today",
    dueTomorrow: "Due tomorrow",
    dueInDays: "Due in",
    days: "days",
    daysLeft: "days left",
    daysOverdue: "d overdue",
    noDeadline: "No deadline",
    allCaughtUp: "All caught up!",
    noPendingTasks: "No pending tasks assigned to you.",
    notifications: "Notifications",
    viewAllTasks: "View all my tasks →",
    totalTasks: "Total Tasks",
    completion: "Completion",
    upcomingDeadlines: "Upcoming Deadlines",
    noDeadlinesSet: "No deadlines set",
    taskTimeline: "Task Timeline",
    teamMembers: "Team Members",
    manage: "Manage",
    noMembersYet: "No members added yet",
    noUpcomingDeadlines: "No upcoming deadlines",
    addMember: "Add Member",
    removeMember: "Remove",
    selectMember: "Select a member...",
    spaceMembersTitle: "Space Members",
    noMembersInSpace: "No members in this space",
    noMembersSpace: "No members have been added to this space.",
    completed: "Completed",
    created: "Created",
    noActivityYet: "No activity yet",
    allFilter: "All",
    allPriorities: "All Priorities",
    searchCompleted: "Search completed tasks...",
    noCompletedTasks: "No completed tasks",
    noMatchingTasks: "No matching tasks",
    completedTasksTry: "Tasks you complete will appear here.",
    adjustFilters: "Try adjusting your search or filters.",
    name: "Name",
    company: "Company",
    phone: "Phone",
    url: "URL",
    notes: "Notes (optional)",
    addToFolder: "Add to folder (optional)",
    rootFolder: "Root (no folder)",
    adding: "Adding...",
    noSendersYet: "No senders yet",
    sendersDesc: "Manage task sources and senders",
    addSenderTitle: "Add Sender",
    makeAdmin: "Make Admin",
    removeAdminRole: "Remove Admin",
    searchTasksSpaces: "Search tasks, spaces...",
    typeToSearch: "Type to search tasks and spaces...",
    noResultsFor: "No results for",
    adminRequired: "Admin access required",
    // Bug Tracker
    bugTracker: "Bug Tracker",
    bugs: "Bugs",
    newBug: "New Bug",
    bugSeverity: "Severity",
    critical: "Critical",
    high: "High",
    medium: "Medium",
    low: "Low",
    openBugs: "Open Bugs",
    resolvedBugs: "Resolved",
    allBugs: "All Bugs",
    noBugsYet: "No bugs reported",
    noBugsDesc: "When bugs are reported they will appear here.",
    stepsToReproduce: "Steps to Reproduce",
    expectedBehavior: "Expected Behavior",
    actualBehavior: "Actual Behavior",
    bugDetails: "Bug Details",
    taskType: "Type",
    allTypes: "All Types",
    bugTab: "Bugs",
    // Task types
    typeTask: "Task",
    typeBug: "Bug",
    typeFeature: "Feature",
    typeImprovement: "Improvement",
    // Team performance
    teamPerformance: "Team Performance",
    tasksByMember: "Tasks by Member",
    taskDistribution: "Task Distribution",
    completionRate: "Completion Rate",
    employeeStats: "Employee Statistics",
    activeTasks: "Active Tasks",
    completedTasks: "Completed",
    noDataYet: "No data yet",
    // Checklist
    checklist: "Checklist",
    addChecklistItem: "Add item...",
    // Tags
    tags: "Tags",
    addTag: "Add tag",
    // ── NEW FEATURES ─────────────────────────────────────────────────────────
    // Subtasks
    subtasks: "Subtasks",
    addSubtask: "Add subtask",
    noSubtasks: "No subtasks yet",
    subtaskPlaceholder: "Subtask title...",
    subtaskProgress: "subtasks done",
    // Time Tracking
    timeTracking: "Time Tracking",
    startTimer: "Start Timer",
    stopTimer: "Stop Timer",
    logTime: "Log Time",
    timeLogged: "Time Logged",
    totalTimeTracked: "Total Time",
    addTimeEntry: "Add Time Entry",
    hoursShort: "h",
    minutesShort: "m",
    billable: "Billable",
    noTimeLogged: "No time logged yet",
    timerNote: "Note (optional)",
    timerRunning: "Running",
    // Dependencies
    dependencies: "Dependencies",
    addDependency: "Add Dependency",
    blockedByLabel: "Blocked By",
    blockingLabel: "Blocking",
    relatedToLabel: "Related To",
    duplicateOfLabel: "Duplicate Of",
    noDependencies: "No dependencies",
    selectTask: "Select a task...",
    // Recurring
    repeating: "Repeating",
    recurrence: "Recurrence",
    repeatTask: "Repeat Task",
    neverRepeat: "Never (one-time)",
    daily: "Daily",
    weekly: "Weekly",
    monthly: "Monthly",
    yearly: "Yearly",
    // Story Points / Start Date / Watchers
    storyPoints: "Story Points",
    startDate: "Start Date",
    watchers: "Watchers",
    watchTask: "Watch",
    unwatchTask: "Unwatch",
    watching: "Watching",
    // Goals
    goals: "Goals",
    newGoal: "New Goal",
    createGoal: "Create Goal",
    goalTitle: "Goal Title",
    goalDescription: "Goal Description",
    targetValue: "Target Value",
    currentValue: "Current Value",
    goalType: "Goal Type",
    numberGoal: "Number",
    percentGoal: "Percentage (%)",
    booleanGoal: "True / False",
    currencyGoal: "Currency",
    noGoals: "No goals yet",
    noGoalsDesc: "Create goals to track your team's biggest targets.",
    goalProgress: "Goal Progress",
    onTrack: "On Track",
    atRisk: "At Risk",
    offTrack: "Off Track",
    goalFolders: "Folders",
    updateProgress: "Update Progress",
    linkTasks: "Link Tasks",
    goalStatus: "Status",
    // My Tasks
    myTasks: "My Tasks",
    todayLabel: "Today",
    upcomingLabel: "Upcoming",
    overdueLabel: "Overdue",
    allTasksLabel: "All",
    noMyTasks: "You have no tasks",
    noMyTasksDesc: "Tasks assigned to you will appear here.",
    // Sprints
    sprints: "Sprints",
    newSprint: "New Sprint",
    createSprint: "Create Sprint",
    sprintName: "Sprint Name",
    sprintGoal: "Sprint Goal",
    sprintStart: "Start Date",
    sprintEnd: "End Date",
    backlog: "Backlog",
    activeSprint: "Active Sprint",
    completeSprint: "Complete Sprint",
    addToSprint: "Add to Sprint",
    moveToBacklog: "Move to Backlog",
    sprintPoints: "Points",
    noSprints: "No sprints yet",
    noSprintsDesc: "Create your first sprint to organize your work into iterations.",
    sprintCompleted: "Completed",
    planningSprint: "Planning",
    activeSprnt: "Active",
    sprintBurndown: "Burndown",
    velocity: "Velocity",
    // Automations
    automations: "Automations",
    newAutomation: "New Automation",
    createAutomation: "Create Automation",
    automationName: "Automation Name",
    triggerLabel: "Trigger — When",
    conditionLabel: "Condition — If",
    actionLabel: "Action — Then",
    noAutomations: "No automations yet",
    noAutomationsDesc: "Automate repetitive work with simple if-then rules.",
    enabledLabel: "Enabled",
    automationRuns: "Runs",
    whenStatusChanges: "Status changes to",
    whenPriorityChanges: "Priority changes to",
    whenAssigneeAdded: "Assignee is added",
    whenTaskCreated: "Task is created",
    whenDueDateReaches: "Due date reaches",
    thenChangeStatus: "Change status to",
    thenChangePriority: "Change priority to",
    thenAssign: "Assign to member",
    thenNotify: "Send notification",
    thenCreateTask: "Create a new task",
    // Inbox
    inbox: "Inbox",
    markAllRead: "Mark all read",
    unreadLabel: "Unread",
    mentionsLabel: "Mentions",
    assignmentsLabel: "Assignments",
    noNotificationsYet: "No notifications yet",
    noNotificationsDesc: "Activity and mentions will appear here.",
    markRead: "Mark as read",
    notifType: "Type",
    // Workload
    workloadView: "Workload",
    memberCapacity: "Capacity",
    overloaded: "Overloaded",
    underloaded: "Underloaded",
    balanced: "Balanced",
    hoursPerDay: "hrs/day",
    workloadTitle: "Workload View",
    setCapacity: "Set Capacity",
    // Calendar View
    calendarView: "Calendar",
    monthView: "Month",
    weekView: "Week",
    dayView: "Day",
    noTasksOnDay: "No tasks",
    // Table View
    tableView: "Table",
    // Gantt View
    ganttView: "Gantt",
    // Portfolio
    portfolio: "Portfolio",
    projectHealth: "Project Health",
    noProjects: "No projects to display",
    // Chat
    chat: "Chat",
    channels: "Channels",
    directMessages: "Direct Messages",
    newChannel: "New Channel",
    channelNamePlaceholder: "channel-name",
    typeMessage: "Type a message...",
    noMessages: "No messages yet",
    noMessagesDesc: "Start the conversation!",
    generalChannel: "general",
    // Forms
    forms: "Forms",
    newForm: "New Form",
    createForm: "Create Form",
    formTitleLabel: "Form Title",
    publicFormLink: "Public Link",
    formSubmissions: "Submissions",
    noForms: "No forms yet",
    noFormsDesc: "Create forms to collect task requests from anyone.",
    copyLink: "Copy Link",
    submitForm: "Submit",
    formField: "Field",
    addFormField: "Add Field",
    fieldType: "Field Type",
    fieldLabel: "Field Label",
    required: "Required",
    textField: "Text",
    numberField: "Number",
    dateField: "Date",
    dropdownField: "Dropdown",
    checkboxField: "Checkbox",
    formLinkedSpace: "Linked Space",
    // Custom Fields
    customFields: "Custom Fields",
    addCustomField: "Add Custom Field",
    noCustomFields: "No custom fields",
    noCustomFieldsDesc: "Add custom fields to capture extra info on your tasks.",
    fieldName: "Field Name",
    // Kanban
    kanbanView: "Board",
    // Subspaces
    subspacesTab: "Sub-spaces",
    // Shared
    close: "Close",
    confirm: "Confirm",
    none: "None",
    type: "Type",
    value: "Value",
    of: "of",
    from: "from",
  },
  ar: {
    dashboard: "لوحة التحكم",
    spaces: "المساحات",
    timeline: "الجدول الزمني",
    history: "السجل",
    members: "الأعضاء",
    senders: "المرسلون",
    settings: "الإعدادات",
    menu: "القائمة",
    workspace: "مساحة العمل",
    lightMode: "الوضع الفاتح",
    darkMode: "الوضع الداكن",
    mySpaces: "مساحاتي",
    welcomeBack: "مرحباً بك",
    signInSubtitle: "سجّل دخولك لحساب مساحة العمل",
    email: "البريد الإلكتروني",
    password: "كلمة المرور",
    signIn: "تسجيل الدخول",
    signingIn: "جاري الدخول...",
    noAccount: "ليس لديك حساب؟",
    signUp: "إنشاء حساب",
    createAccount: "إنشاء حساب",
    alreadyHaveAccount: "لديك حساب بالفعل؟",
    fullName: "الاسم الكامل",
    yourFullName: "اسمك الكامل",
    confirmPassword: "تأكيد كلمة المرور",
    minChars: "٦ أحرف على الأقل",
    signingUp: "جاري إنشاء الحساب...",
    joinWorkspace: "سجّل للانضمام لمساحة عمل فريقك",
    newSpace: "مساحة جديدة",
    searchSpaces: "ابحث عن مساحة...",
    createSpace: "إنشاء مساحة",
    spaceName: "الاسم",
    spaceDesc: "الوصف",
    spaceColor: "اللون",
    noSpacesFound: "لا توجد مساحات",
    createFirstSpace: "أنشئ مساحتك الأولى لتبدأ تنظيم المهام.",
    notInAnySpace: "لم تُضف إلى أي مساحة بعد.",
    tasks: "مهام",
    membersLabel: "أعضاء",
    creating: "جاري الإنشاء...",
    cancel: "إلغاء",
    overview: "نظرة عامة",
    tasksTab: "المهام",
    timelineTab: "الجدول",
    membersTab: "الأعضاء",
    data: "الملفات",
    filesLinks: "الملفات والروابط",
    newFolder: "مجلد جديد",
    addLink: "إضافة رابط",
    createFolder: "إنشاء مجلد",
    emptyFolder: "مجلد فارغ",
    noFilesYet: "لا توجد ملفات أو روابط",
    noFilesDesc: "أنشئ مجلدات وأضف روابط لتنظيم موارد مساحتك.",
    noFilesAdded: "لم تُضف أي ملفات أو روابط بعد.",
    newTask: "مهمة جديدة",
    createTask: "إنشاء مهمة",
    taskTitle: "عنوان المهمة...",
    description: "الوصف (اختياري)",
    status: "الحالة",
    priority: "الأولوية",
    deadline: "الموعد النهائي",
    estimatedHours: "الساعات المقدّرة",
    estimatedHoursLabel: "الساعات المقدّرة",
    assignMembers: "تعيين الأعضاء",
    assignees: "المُعيَّنون",
    sender: "المرسل",
    senderFrom: "المرسل (من المدير)",
    noTasksYet: "لا توجد مهام بعد",
    noTaskFound: "المهمة غير موجودة",
    progress: "التقدم",
    activity: "النشاط",
    writeComment: "اكتب تعليقاً...",
    sendReminder: "إرسال تذكير",
    backToSpace: "العودة للمساحة",
    deleteTask: "حذف المهمة",
    deleteSpace: "حذف المساحة",
    profileSettings: "إعدادات الملف الشخصي",
    webhookSettings: "إعدادات Webhook",
    saveChanges: "حفظ التغييرات",
    saving: "جاري الحفظ...",
    loading: "جاري التحميل...",
    delete: "حذف",
    edit: "تعديل",
    add: "إضافة",
    save: "حفظ",
    search: "بحث...",
    noResults: "لا توجد نتائج",
    overdue: "متأخر",
    dueSoon: "قريب الموعد",
    inProgress: "قيد التنفيذ",
    done: "مكتمل",
    blocked: "محظور",
    todo: "للتنفيذ",
    review: "مراجعة",
    today: "اليوم",
    tomorrow: "غداً",
    dueToday: "مستحق اليوم",
    dueTomorrow: "مستحق غداً",
    dueInDays: "مستحق خلال",
    days: "أيام",
    daysLeft: "أيام متبقية",
    daysOverdue: "يوم متأخر",
    noDeadline: "بدون موعد",
    allCaughtUp: "أنت محدّث!",
    noPendingTasks: "لا توجد مهام معلّقة معيّنة لك.",
    notifications: "الإشعارات",
    viewAllTasks: "عرض كل مهامي ←",
    totalTasks: "إجمالي المهام",
    completion: "نظرة عامة",
    upcomingDeadlines: "المواعيد القادمة",
    noDeadlinesSet: "لا توجد مواعيد محددة",
    taskTimeline: "جدول المهام",
    teamMembers: "أعضاء الفريق",
    manage: "إدارة",
    noMembersYet: "لم يُضف أعضاء بعد",
    noUpcomingDeadlines: "لا توجد مواعيد قادمة",
    addMember: "إضافة عضو",
    removeMember: "إزالة",
    selectMember: "اختر عضواً...",
    spaceMembersTitle: "أعضاء المساحة",
    noMembersInSpace: "لا يوجد أعضاء في هذه المساحة",
    noMembersSpace: "لم يُضف أي أعضاء لهذه المساحة.",
    completed: "مكتمل",
    created: "تاريخ الإنشاء",
    noActivityYet: "لا يوجد نشاط بعد",
    allFilter: "الكل",
    allPriorities: "كل الأولويات",
    searchCompleted: "ابحث في المهام المكتملة...",
    noCompletedTasks: "لا توجد مهام مكتملة",
    noMatchingTasks: "لا توجد مهام مطابقة",
    completedTasksTry: "المهام التي تكملها ستظهر هنا.",
    adjustFilters: "جرّب تعديل البحث أو الفلاتر.",
    name: "الاسم",
    company: "الشركة",
    phone: "الهاتف",
    url: "الرابط",
    notes: "ملاحظات (اختياري)",
    addToFolder: "إضافة إلى مجلد (اختياري)",
    rootFolder: "الرئيسي (بدون مجلد)",
    adding: "جاري الإضافة...",
    noSendersYet: "لا يوجد مرسلون",
    sendersDesc: "إدارة مصادر المهام والمرسلين",
    addSenderTitle: "إضافة مرسل",
    makeAdmin: "تعيين مسؤولاً",
    removeAdminRole: "إزالة كمسؤول",
    searchTasksSpaces: "ابحث في المهام والمساحات...",
    typeToSearch: "اكتب للبحث في المهام والمساحات...",
    noResultsFor: "لا نتائج لـ",
    adminRequired: "يلزم صلاحية المسؤول",
    // Bug Tracker
    bugTracker: "متتبع الأخطاء",
    bugs: "الأخطاء",
    newBug: "خطأ جديد",
    bugSeverity: "الخطورة",
    critical: "حرج",
    high: "عالي",
    medium: "متوسط",
    low: "منخفض",
    openBugs: "الأخطاء المفتوحة",
    resolvedBugs: "المحلولة",
    allBugs: "كل الأخطاء",
    noBugsYet: "لا توجد أخطاء مُبلَّغ عنها",
    noBugsDesc: "ستظهر الأخطاء المُبلَّغ عنها هنا.",
    stepsToReproduce: "خطوات إعادة الإنتاج",
    expectedBehavior: "السلوك المتوقع",
    actualBehavior: "السلوك الفعلي",
    bugDetails: "تفاصيل الخطأ",
    taskType: "النوع",
    allTypes: "كل الأنواع",
    bugTab: "الأخطاء",
    // Task types
    typeTask: "مهمة",
    typeBug: "خطأ",
    typeFeature: "ميزة",
    typeImprovement: "تحسين",
    // Team performance
    teamPerformance: "أداء الفريق",
    tasksByMember: "المهام لكل عضو",
    taskDistribution: "توزيع المهام",
    completionRate: "معدل الإنجاز",
    employeeStats: "إحصائيات الموظفين",
    activeTasks: "المهام النشطة",
    completedTasks: "المكتملة",
    noDataYet: "لا توجد بيانات بعد",
    // Checklist
    checklist: "قائمة المراجعة",
    addChecklistItem: "أضف عنصراً...",
    // Tags
    tags: "العلامات",
    addTag: "إضافة علامة",
    // ── NEW FEATURES ─────────────────────────────────────────────────────────
    // Subtasks
    subtasks: "المهام الفرعية",
    addSubtask: "إضافة مهمة فرعية",
    noSubtasks: "لا توجد مهام فرعية",
    subtaskPlaceholder: "عنوان المهمة الفرعية...",
    subtaskProgress: "مهمة فرعية مكتملة",
    // Time Tracking
    timeTracking: "تتبع الوقت",
    startTimer: "بدء المؤقت",
    stopTimer: "إيقاف المؤقت",
    logTime: "تسجيل الوقت",
    timeLogged: "الوقت المسجل",
    totalTimeTracked: "إجمالي الوقت",
    addTimeEntry: "إضافة إدخال وقت",
    hoursShort: "س",
    minutesShort: "د",
    billable: "قابل للفوترة",
    noTimeLogged: "لم يُسجَّل وقت بعد",
    timerNote: "ملاحظة (اختياري)",
    timerRunning: "يعمل",
    // Dependencies
    dependencies: "التبعيات",
    addDependency: "إضافة تبعية",
    blockedByLabel: "محظور بواسطة",
    blockingLabel: "يحظر",
    relatedToLabel: "مرتبط بـ",
    duplicateOfLabel: "نسخة من",
    noDependencies: "لا توجد تبعيات",
    selectTask: "اختر مهمة...",
    // Recurring
    repeating: "متكرر",
    recurrence: "التكرار",
    repeatTask: "تكرار المهمة",
    neverRepeat: "لا يتكرر (مرة واحدة)",
    daily: "يومي",
    weekly: "أسبوعي",
    monthly: "شهري",
    yearly: "سنوي",
    // Story Points / Start Date / Watchers
    storyPoints: "نقاط القصة",
    startDate: "تاريخ البدء",
    watchers: "المتابعون",
    watchTask: "متابعة",
    unwatchTask: "إلغاء المتابعة",
    watching: "تتابع",
    // Goals
    goals: "الأهداف",
    newGoal: "هدف جديد",
    createGoal: "إنشاء هدف",
    goalTitle: "عنوان الهدف",
    goalDescription: "وصف الهدف",
    targetValue: "القيمة المستهدفة",
    currentValue: "القيمة الحالية",
    goalType: "نوع الهدف",
    numberGoal: "رقمي",
    percentGoal: "نسبة مئوية (%)",
    booleanGoal: "صح / خطأ",
    currencyGoal: "عملة",
    noGoals: "لا توجد أهداف بعد",
    noGoalsDesc: "أنشئ أهدافاً لتتبع أكبر أهداف فريقك.",
    goalProgress: "تقدم الهدف",
    onTrack: "في المسار",
    atRisk: "في خطر",
    offTrack: "خارج المسار",
    goalFolders: "المجلدات",
    updateProgress: "تحديث التقدم",
    linkTasks: "ربط المهام",
    goalStatus: "الحالة",
    // My Tasks
    myTasks: "مهامي",
    todayLabel: "اليوم",
    upcomingLabel: "القادمة",
    overdueLabel: "المتأخرة",
    allTasksLabel: "الكل",
    noMyTasks: "لا توجد مهام",
    noMyTasksDesc: "المهام المعيّنة لك ستظهر هنا.",
    // Sprints
    sprints: "السبرنتات",
    newSprint: "سبرنت جديد",
    createSprint: "إنشاء سبرنت",
    sprintName: "اسم السبرنت",
    sprintGoal: "هدف السبرنت",
    sprintStart: "تاريخ البدء",
    sprintEnd: "تاريخ الانتهاء",
    backlog: "البكلوج",
    activeSprint: "السبرنت النشط",
    completeSprint: "إكمال السبرنت",
    addToSprint: "إضافة للسبرنت",
    moveToBacklog: "نقل للبكلوج",
    sprintPoints: "النقاط",
    noSprints: "لا توجد سبرنتات",
    noSprintsDesc: "أنشئ سبرنتك الأول لتنظيم عملك في تكرارات.",
    sprintCompleted: "مكتمل",
    planningSprint: "تخطيط",
    activeSprnt: "نشط",
    sprintBurndown: "مخطط الإتمام",
    velocity: "السرعة",
    // Automations
    automations: "الأتمتة",
    newAutomation: "أتمتة جديدة",
    createAutomation: "إنشاء أتمتة",
    automationName: "اسم الأتمتة",
    triggerLabel: "المحفز — عندما",
    conditionLabel: "الشرط — إذا",
    actionLabel: "الإجراء — ثم",
    noAutomations: "لا توجد أتمتة",
    noAutomationsDesc: "أتمت المهام المتكررة بقواعد بسيطة.",
    enabledLabel: "مفعّل",
    automationRuns: "التشغيلات",
    whenStatusChanges: "تتغير الحالة إلى",
    whenPriorityChanges: "تتغير الأولوية إلى",
    whenAssigneeAdded: "يُضاف منتسب",
    whenTaskCreated: "تُنشأ مهمة",
    whenDueDateReaches: "يصل الموعد النهائي",
    thenChangeStatus: "تغيير الحالة إلى",
    thenChangePriority: "تغيير الأولوية إلى",
    thenAssign: "تعيين لعضو",
    thenNotify: "إرسال إشعار",
    thenCreateTask: "إنشاء مهمة جديدة",
    // Inbox
    inbox: "البريد الوارد",
    markAllRead: "تعليم الكل كمقروء",
    unreadLabel: "غير مقروء",
    mentionsLabel: "الإشارات",
    assignmentsLabel: "التعيينات",
    noNotificationsYet: "لا توجد إشعارات",
    noNotificationsDesc: "ستظهر النشاطات والإشارات هنا.",
    markRead: "تعليم كمقروء",
    notifType: "النوع",
    // Workload
    workloadView: "التحميل",
    memberCapacity: "الطاقة",
    overloaded: "محمّل زيادة",
    underloaded: "تحميل منخفض",
    balanced: "متوازن",
    hoursPerDay: "ساعة/يوم",
    workloadTitle: "عرض التحميل",
    setCapacity: "تحديد الطاقة",
    // Calendar View
    calendarView: "التقويم",
    monthView: "الشهر",
    weekView: "الأسبوع",
    dayView: "اليوم",
    noTasksOnDay: "لا توجد مهام",
    // Table View
    tableView: "الجدول",
    // Gantt View
    ganttView: "جانت",
    // Portfolio
    portfolio: "المحفظة",
    projectHealth: "صحة المشروع",
    noProjects: "لا توجد مشاريع",
    // Chat
    chat: "المحادثة",
    channels: "القنوات",
    directMessages: "الرسائل المباشرة",
    newChannel: "قناة جديدة",
    channelNamePlaceholder: "اسم-القناة",
    typeMessage: "اكتب رسالة...",
    noMessages: "لا توجد رسائل",
    noMessagesDesc: "ابدأ المحادثة!",
    generalChannel: "عام",
    // Forms
    forms: "النماذج",
    newForm: "نموذج جديد",
    createForm: "إنشاء نموذج",
    formTitleLabel: "عنوان النموذج",
    publicFormLink: "الرابط العام",
    formSubmissions: "الإجابات",
    noForms: "لا توجد نماذج",
    noFormsDesc: "أنشئ نماذج لجمع طلبات المهام من أي شخص.",
    copyLink: "نسخ الرابط",
    submitForm: "إرسال",
    formField: "حقل",
    addFormField: "إضافة حقل",
    fieldType: "نوع الحقل",
    fieldLabel: "عنوان الحقل",
    required: "مطلوب",
    textField: "نص",
    numberField: "رقم",
    dateField: "تاريخ",
    dropdownField: "قائمة منسدلة",
    checkboxField: "خانة اختيار",
    formLinkedSpace: "المساحة المرتبطة",
    // Custom Fields
    customFields: "الحقول المخصصة",
    addCustomField: "إضافة حقل مخصص",
    noCustomFields: "لا توجد حقول مخصصة",
    noCustomFieldsDesc: "أضف حقولاً مخصصة لالتقاط معلومات إضافية في مهامك.",
    fieldName: "اسم الحقل",
    // Kanban
    kanbanView: "اللوحة",
    // Subspaces
    subspacesTab: "المساحات الفرعية",
    // Shared
    close: "إغلاق",
    confirm: "تأكيد",
    none: "لا شيء",
    type: "النوع",
    value: "القيمة",
    of: "من",
    from: "من",
  },
} as const;

export type Translations = typeof translations.en;

interface LangContextType {
  lang: Lang;
  setLang: (l: Lang) => void;
  t: Translations;
  isRTL: boolean;
}

const LangContext = createContext<LangContextType>({
  lang: "en",
  setLang: () => {},
  t: translations.en,
  isRTL: false,
});

export const LangProvider = ({ children }: { children: ReactNode }) => {
  const [lang, setLangState] = useState<Lang>(() => {
    return (localStorage.getItem("bod-lang") as Lang) || "en";
  });

  const setLang = (l: Lang) => {
    setLangState(l);
    localStorage.setItem("bod-lang", l);
    document.documentElement.dir = l === "ar" ? "rtl" : "ltr";
    document.documentElement.lang = l;
  };

  const t = translations[lang] as Translations;
  const isRTL = lang === "ar";

  if (typeof document !== "undefined") {
    document.documentElement.dir = isRTL ? "rtl" : "ltr";
    document.documentElement.lang = lang;
  }

  return (
    <LangContext.Provider value={{ lang, setLang, t, isRTL }}>
      {children}
    </LangContext.Provider>
  );
};

export const useLang = () => useContext(LangContext);
