import { createContext, useContext, useState, ReactNode } from "react";

export type Lang = "ar" | "en";

const translations = {
  en: {
    dashboard: "Dashboard",
    spaces: "Spaces",
    timeline: "Timeline",
    history: "History",
    members: "Members",
    senders: "Senders",
    settings: "Settings",
    menu: "Menu",
    workspace: "Workspace",
    lightMode: "Light mode",
    darkMode: "Dark mode",
    mySpaces: "My Spaces",
    welcomeBack: "Welcome back",
    signInSubtitle: "Sign in to your workspace account",
    email: "Email",
    password: "Password",
    signIn: "Sign in",
    signingIn: "Signing in...",
    noAccount: "Don't have an account?",
    signUp: "Sign up",
    createAccount: "Create Account",
    alreadyHaveAccount: "Already have an account?",
    fullName: "Full Name",
    yourFullName: "Your full name",
    confirmPassword: "Confirm Password",
    minChars: "Min. 6 characters",
    signingUp: "Creating account...",
    joinWorkspace: "Sign up to join your team workspace",
    newSpace: "New Space",
    searchSpaces: "Search spaces...",
    createSpace: "Create Space",
    spaceName: "Name",
    spaceDesc: "Description",
    spaceColor: "Color",
    noSpacesFound: "No spaces found",
    createFirstSpace: "Create your first space to start organizing tasks.",
    notInAnySpace: "You haven't been added to any spaces yet.",
    tasks: "tasks",
    membersLabel: "members",
    creating: "Creating...",
    cancel: "Cancel",
    overview: "Overview",
    tasksTab: "Tasks",
    timelineTab: "Timeline",
    membersTab: "Members",
    data: "Data",
    filesLinks: "Files & Links",
    newFolder: "New Folder",
    addLink: "Add Link",
    createFolder: "Create Folder",
    emptyFolder: "Empty folder",
    noFilesYet: "No files or links yet",
    noFilesDesc: "Create folders and add links to organize your space resources.",
    noFilesAdded: "No files or links have been added yet.",
    newTask: "New Task",
    createTask: "Create Task",
    taskTitle: "Task title...",
    description: "Description (optional)",
    status: "Status",
    priority: "Priority",
    deadline: "Deadline",
    estimatedHours: "Est. Hours",
    estimatedHoursLabel: "Estimated Hours",
    assignMembers: "Assign Members",
    assignees: "Assignees",
    sender: "Sender",
    senderFrom: "Sender (from manager)",
    noTasksYet: "No tasks yet",
    noTaskFound: "Task not found",
    progress: "Progress",
    activity: "Activity",
    writeComment: "Write a comment...",
    sendReminder: "Send Reminder",
    backToSpace: "Back to space",
    deleteTask: "Delete Task",
    deleteSpace: "Delete Space",
    profileSettings: "Profile Settings",
    webhookSettings: "Webhook Settings",
    saveChanges: "Save Changes",
    saving: "Saving...",
    loading: "Loading...",
    delete: "Delete",
    edit: "Edit",
    add: "Add",
    save: "Save",
    search: "Search...",
    noResults: "No results",
    overdue: "Overdue",
    dueSoon: "Due Soon",
    inProgress: "In Progress",
    done: "Done",
    blocked: "Blocked",
    todo: "To Do",
    review: "Review",
    today: "Today",
    tomorrow: "Tomorrow",
    dueToday: "Due today",
    dueTomorrow: "Due tomorrow",
    dueInDays: "Due in",
    days: "days",
    daysLeft: "days left",
    daysOverdue: "d overdue",
    noDeadline: "No deadline",
    allCaughtUp: "All caught up!",
    noPendingTasks: "No pending tasks assigned to you.",
    notifications: "Notifications",
    viewAllTasks: "View all my tasks →",
    totalTasks: "Total Tasks",
    completion: "Completion",
    upcomingDeadlines: "Upcoming Deadlines",
    noDeadlinesSet: "No deadlines set",
    taskTimeline: "Task Timeline",
    teamMembers: "Team Members",
    manage: "Manage",
    noMembersYet: "No members added yet",
    noUpcomingDeadlines: "No upcoming deadlines",
    addMember: "Add Member",
    removeMember: "Remove",
    selectMember: "Select a member...",
    spaceMembersTitle: "Space Members",
    noMembersInSpace: "No members in this space",
    noMembersSpace: "No members have been added to this space.",
    completed: "Completed",
    created: "Created",
    noActivityYet: "No activity yet",
    allFilter: "All",
    allPriorities: "All Priorities",
    searchCompleted: "Search completed tasks...",
    noCompletedTasks: "No completed tasks",
    noMatchingTasks: "No matching tasks",
    completedTasksTry: "Tasks you complete will appear here.",
    adjustFilters: "Try adjusting your search or filters.",
    name: "Name",
    company: "Company",
    phone: "Phone",
    url: "URL",
    notes: "Notes (optional)",
    addToFolder: "Add to folder (optional)",
    rootFolder: "Root (no folder)",
    adding: "Adding...",
    noSendersYet: "No senders yet",
    sendersDesc: "Manage task sources and senders",
    addSenderTitle: "Add Sender",
    makeAdmin: "Make Admin",
    removeAdminRole: "Remove Admin",
    searchTasksSpaces: "Search tasks, spaces...",
    typeToSearch: "Type to search tasks and spaces...",
    noResultsFor: "No results for",
    adminRequired: "Admin access required",
  },
  ar: {
    dashboard: "لوحة التحكم",
    spaces: "المساحات",
    timeline: "الجدول الزمني",
    history: "السجل",
    members: "الأعضاء",
    senders: "المرسلون",
    settings: "الإعدادات",
    menu: "القائمة",
    workspace: "مساحة العمل",
    lightMode: "الوضع الفاتح",
    darkMode: "الوضع الداكن",
    mySpaces: "مساحاتي",
    welcomeBack: "مرحباً بك",
    signInSubtitle: "سجّل دخولك لحساب مساحة العمل",
    email: "البريد الإلكتروني",
    password: "كلمة المرور",
    signIn: "تسجيل الدخول",
    signingIn: "جاري الدخول...",
    noAccount: "ليس لديك حساب؟",
    signUp: "إنشاء حساب",
    createAccount: "إنشاء حساب",
    alreadyHaveAccount: "لديك حساب بالفعل؟",
    fullName: "الاسم الكامل",
    yourFullName: "اسمك الكامل",
    confirmPassword: "تأكيد كلمة المرور",
    minChars: "٦ أحرف على الأقل",
    signingUp: "جاري إنشاء الحساب...",
    joinWorkspace: "سجّل للانضمام لمساحة عمل فريقك",
    newSpace: "مساحة جديدة",
    searchSpaces: "ابحث عن مساحة...",
    createSpace: "إنشاء مساحة",
    spaceName: "الاسم",
    spaceDesc: "الوصف",
    spaceColor: "اللون",
    noSpacesFound: "لا توجد مساحات",
    createFirstSpace: "أنشئ مساحتك الأولى لتبدأ تنظيم المهام.",
    notInAnySpace: "لم تُضف إلى أي مساحة بعد.",
    tasks: "مهام",
    membersLabel: "أعضاء",
    creating: "جاري الإنشاء...",
    cancel: "إلغاء",
    overview: "نظرة عامة",
    tasksTab: "المهام",
    timelineTab: "الجدول",
    membersTab: "الأعضاء",
    data: "الملفات",
    filesLinks: "الملفات والروابط",
    newFolder: "مجلد جديد",
    addLink: "إضافة رابط",
    createFolder: "إنشاء مجلد",
    emptyFolder: "مجلد فارغ",
    noFilesYet: "لا توجد ملفات أو روابط",
    noFilesDesc: "أنشئ مجلدات وأضف روابط لتنظيم موارد مساحتك.",
    noFilesAdded: "لم تُضف أي ملفات أو روابط بعد.",
    newTask: "مهمة جديدة",
    createTask: "إنشاء مهمة",
    taskTitle: "عنوان المهمة...",
    description: "الوصف (اختياري)",
    status: "الحالة",
    priority: "الأولوية",
    deadline: "الموعد النهائي",
    estimatedHours: "الساعات المقدّرة",
    estimatedHoursLabel: "الساعات المقدّرة",
    assignMembers: "تعيين الأعضاء",
    assignees: "المُعيَّنون",
    sender: "المرسل",
    senderFrom: "المرسل (من المدير)",
    noTasksYet: "لا توجد مهام بعد",
    noTaskFound: "المهمة غير موجودة",
    progress: "التقدم",
    activity: "النشاط",
    writeComment: "اكتب تعليقاً...",
    sendReminder: "إرسال تذكير",
    backToSpace: "العودة للمساحة",
    deleteTask: "حذف المهمة",
    deleteSpace: "حذف المساحة",
    profileSettings: "إعدادات الملف الشخصي",
    webhookSettings: "إعدادات Webhook",
    saveChanges: "حفظ التغييرات",
    saving: "جاري الحفظ...",
    loading: "جاري التحميل...",
    delete: "حذف",
    edit: "تعديل",
    add: "إضافة",
    save: "حفظ",
    search: "بحث...",
    noResults: "لا توجد نتائج",
    overdue: "متأخر",
    dueSoon: "قريب الموعد",
    inProgress: "قيد التنفيذ",
    done: "مكتمل",
    blocked: "محظور",
    todo: "للتنفيذ",
    review: "مراجعة",
    today: "اليوم",
    tomorrow: "غداً",
    dueToday: "مستحق اليوم",
    dueTomorrow: "مستحق غداً",
    dueInDays: "مستحق خلال",
    days: "أيام",
    daysLeft: "أيام متبقية",
    daysOverdue: "يوم متأخر",
    noDeadline: "بدون موعد",
    allCaughtUp: "أنت محدّث!",
    noPendingTasks: "لا توجد مهام معلّقة معيّنة لك.",
    notifications: "الإشعارات",
    viewAllTasks: "عرض كل مهامي ←",
    totalTasks: "إجمالي المهام",
    completion: "نظرة عامة",
    upcomingDeadlines: "المواعيد القادمة",
    noDeadlinesSet: "لا توجد مواعيد محددة",
    taskTimeline: "جدول المهام",
    teamMembers: "أعضاء الفريق",
    manage: "إدارة",
    noMembersYet: "لم يُضف أعضاء بعد",
    noUpcomingDeadlines: "لا توجد مواعيد قادمة",
    addMember: "إضافة عضو",
    removeMember: "إزالة",
    selectMember: "اختر عضواً...",
    spaceMembersTitle: "أعضاء المساحة",
    noMembersInSpace: "لا يوجد أعضاء في هذه المساحة",
    noMembersSpace: "لم يُضف أي أعضاء لهذه المساحة.",
    completed: "مكتمل",
    created: "تاريخ الإنشاء",
    noActivityYet: "لا يوجد نشاط بعد",
    allFilter: "الكل",
    allPriorities: "كل الأولويات",
    searchCompleted: "ابحث في المهام المكتملة...",
    noCompletedTasks: "لا توجد مهام مكتملة",
    noMatchingTasks: "لا توجد مهام مطابقة",
    completedTasksTry: "المهام التي تكملها ستظهر هنا.",
    adjustFilters: "جرّب تعديل البحث أو الفلاتر.",
    name: "الاسم",
    company: "الشركة",
    phone: "الهاتف",
    url: "الرابط",
    notes: "ملاحظات (اختياري)",
    addToFolder: "إضافة إلى مجلد (اختياري)",
    rootFolder: "الرئيسي (بدون مجلد)",
    adding: "جاري الإضافة...",
    noSendersYet: "لا يوجد مرسلون",
    sendersDesc: "إدارة مصادر المهام والمرسلين",
    addSenderTitle: "إضافة مرسل",
    makeAdmin: "تعيين مسؤولاً",
    removeAdminRole: "إزالة كمسؤول",
    searchTasksSpaces: "ابحث في المهام والمساحات...",
    typeToSearch: "اكتب للبحث في المهام والمساحات...",
    noResultsFor: "لا نتائج لـ",
    adminRequired: "يلزم صلاحية المسؤول",
  },
} as const;

export type Translations = typeof translations.en;

interface LangContextType {
  lang: Lang;
  setLang: (l: Lang) => void;
  t: Translations;
  isRTL: boolean;
}

const LangContext = createContext<LangContextType>({
  lang: "en",
  setLang: () => {},
  t: translations.en,
  isRTL: false,
});

export const LangProvider = ({ children }: { children: ReactNode }) => {
  const [lang, setLangState] = useState<Lang>(() => {
    return (localStorage.getItem("bod-lang") as Lang) || "en";
  });

  const setLang = (l: Lang) => {
    setLangState(l);
    localStorage.setItem("bod-lang", l);
    document.documentElement.dir = l === "ar" ? "rtl" : "ltr";
    document.documentElement.lang = l;
  };

  const t = translations[lang] as Translations;
  const isRTL = lang === "ar";

  if (typeof document !== "undefined") {
    document.documentElement.dir = isRTL ? "rtl" : "ltr";
    document.documentElement.lang = lang;
  }

  return (
    <LangContext.Provider value={{ lang, setLang, t, isRTL }}>
      {children}
    </LangContext.Provider>
  );
};

export const useLang = () => useContext(LangContext);
