export const COUNTRY_CODES = [
  { code: "+1", label: "🇺🇸 +1 (US/CA)" },
  { code: "+20", label: "🇪🇬 +20 (Egypt)" },
  { code: "+44", label: "🇬🇧 +44 (UK)" },
  { code: "+49", label: "🇩🇪 +49 (Germany)" },
  { code: "+33", label: "🇫🇷 +33 (France)" },
  { code: "+966", label: "🇸🇦 +966 (Saudi)" },
  { code: "+971", label: "🇦🇪 +971 (UAE)" },
  { code: "+962", label: "🇯🇴 +962 (Jordan)" },
  { code: "+965", label: "🇰🇼 +965 (Kuwait)" },
  { code: "+974", label: "🇶🇦 +974 (Qatar)" },
  { code: "+973", label: "🇧🇭 +973 (Bahrain)" },
  { code: "+968", label: "🇴🇲 +968 (Oman)" },
  { code: "+90", label: "🇹🇷 +90 (Turkey)" },
  { code: "+91", label: "🇮🇳 +91 (India)" },
  { code: "+86", label: "🇨🇳 +86 (China)" },
  { code: "+81", label: "🇯🇵 +81 (Japan)" },
  { code: "+55", label: "🇧🇷 +55 (Brazil)" },
  { code: "+7", label: "🇷🇺 +7 (Russia)" },
];
